# Generated by Django 4.1.7 on 2023-03-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent_level',
            field=models.IntegerField(default=0, verbose_name='Уровень родителя'),
        ),
    ]
