# Generated by Django 4.1.7 on 2023-03-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_remove_menuitem_parent_id_menuitem_parent_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='parent_level',
            new_name='level',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent_id',
            field=models.IntegerField(default=0, verbose_name='id родителя'),
        ),
    ]
