# Generated by Django 4.1.7 on 2023-03-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_rename_parent_level_menuitem_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='level',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='h_level',
            field=models.IntegerField(default=0, verbose_name='Уровень пункта по горизонтали'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='v_level',
            field=models.IntegerField(default=0, verbose_name='Уровень пункта по вертикали'),
        ),
    ]
