# Generated by Django 4.1.7 on 2023-03-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_remove_menuitem_level_menuitem_h_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='v_level',
        ),
    ]
