# Generated by Django 4.1.7 on 2023-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_alter_menuitem_v_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='root_id',
            field=models.IntegerField(default=0, verbose_name='id_прародителя'),
        ),
    ]
